In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
langDataset = pd.read_csv("data/binary.csv")

In [3]:
langDataset.shape

(30000, 10)

In [4]:
langDataset.head()

c_java  c_javascript  c_r  c_php  c_python  c_swift  c_chash  c_cplus  \
0       0             1    0      0         0        0        1        0   
1       0             0    0      0         0        0        0        0   
2       1             1    0      0         0        0        0        0   
3       0             0    0      1         0        0        1        0   
4       0             1    0      1         0        0        0        0   

   c_obj c_os  
0      0    W  
1      0    W  
2      0    W  
3      0    W  
4      0    W

In [5]:
X = langDataset.drop('c_os', axis=1)
y = langDataset['c_os']

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
# SVM Linear

In [49]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [50]:
y_pred = svclassifier.predict(X_test)

In [51]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2190 1272  536]
 [1331 2192  469]
 [1166  868 1976]]
              precision    recall  f1-score   support

           L       0.47      0.55      0.50      3998
           M       0.51      0.55      0.53      3992
           W       0.66      0.49      0.57      4010

    accuracy                           0.53     12000
   macro avg       0.55      0.53      0.53     12000
weighted avg       0.55      0.53      0.53     12000



In [ ]:
# SVM Polynomial

In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1049  631  281]
 [ 644 1129  256]
 [ 469  534 1007]]
              precision    recall  f1-score   support

           L       0.49      0.53      0.51      1961
           M       0.49      0.56      0.52      2029
           W       0.65      0.50      0.57      2010

    accuracy                           0.53      6000
   macro avg       0.54      0.53      0.53      6000
weighted avg       0.54      0.53      0.53      6000



In [ ]:
# SVM Gusian

In [13]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [14]:
y_pred = svclassifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1134  538  289]
 [ 708 1060  261]
 [ 525  460 1025]]
              precision    recall  f1-score   support

           L       0.48      0.58      0.52      1961
           M       0.52      0.52      0.52      2029
           W       0.65      0.51      0.57      2010

    accuracy                           0.54      6000
   macro avg       0.55      0.54      0.54      6000
weighted avg       0.55      0.54      0.54      6000



In [ ]:
# SVM Sigmoid

In [16]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [17]:
y_pred = svclassifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1012  600  349]
 [ 930  761  338]
 [ 758  484  768]]
              precision    recall  f1-score   support

           L       0.37      0.52      0.43      1961
           M       0.41      0.38      0.39      2029
           W       0.53      0.38      0.44      2010

    accuracy                           0.42      6000
   macro avg       0.44      0.42      0.42      6000
weighted avg       0.44      0.42      0.42      6000



In [ ]:
# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [23]:
X = langDataset.drop('c_os', axis=1)
y = langDataset['c_os']

In [24]:
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(X, y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [26]:
p_pred = model.predict_proba(X)
y_pred = model.predict(X)
score_ = model.score(X, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [27]:
print('x:', X, sep='\n')

x:
       c_java  c_javascript  c_r  c_php  c_python  c_swift  c_chash  c_cplus  \
0           0             1    0      0         0        0        1        0   
1           0             0    0      0         0        0        0        0   
2           1             1    0      0         0        0        0        0   
3           0             0    0      1         0        0        1        0   
4           0             1    0      1         0        0        0        0   
...       ...           ...  ...    ...       ...      ...      ...      ...   
29995       1             1    0      0         1        0        0        0   
29996       0             1    0      0         1        0        1        1   
29997       0             0    0      0         0        1        0        0   
29998       0             1    0      0         1        0        0        1   
29999       1             0    0      0         1        1        0        0   

       c_obj  
0          0  
1     

In [28]:
print('y:', y, sep='\n', end='\n\n')

y:
0        W
1        W
2        W
3        W
4        W
        ..
29995    M
29996    M
29997    M
29998    M
29999    M
Name: c_os, Length: 30000, dtype: object



In [29]:
 print('intercept:', model.intercept_)

intercept: [-0.74846822 -0.65675678 -0.77759717]


In [30]:
print('coef:', model.coef_, end='\n\n')

coef: [[ 0.03299647 -0.20749241 -0.07289626  0.27129339  0.6569899  -1.4138026
  -1.19426792  0.69669609 -0.68709463]
 [-0.03915504  0.44889674 -0.13192963 -0.20921209 -0.14148695  1.97442667
  -1.10810201 -0.82032479  1.27503449]
 [ 0.03199166 -0.23393502  0.24026222 -0.05299596 -0.57950981 -1.34905408
   1.89670409 -0.01591123 -0.90702662]]



In [31]:
print('p_pred:', p_pred, sep='\n', end='\n\n')

p_pred:
[[0.1018956  0.20659589 0.69150851]
 [0.32856036 0.34934212 0.32209752]
 [0.28552623 0.44036576 0.27410801]
 ...
 [0.05306734 0.90238759 0.04454507]
 [0.59690699 0.23642553 0.16666748]
 [0.18506991 0.75094273 0.06398736]]



In [32]:
print('y_pred:', y_pred, end='\n\n')

y_pred: ['W' 'M' 'M' ... 'M' 'L' 'M']



In [33]:
print('score_:', score_, end='\n\n')

score_: 0.5377333333333333



In [34]:
print('conf_m:', conf_m, sep='\n', end='\n\n')

conf_m:
[[5559 3080 1361]
 [3274 5510 1216]
 [2403 2534 5063]]



In [35]:
print('report:', report, sep='\n')

report:
              precision    recall  f1-score   support

           L       0.49      0.56      0.52     10000
           M       0.50      0.55      0.52     10000
           W       0.66      0.51      0.57     10000

    accuracy                           0.54     30000
   macro avg       0.55      0.54      0.54     30000
weighted avg       0.55      0.54      0.54     30000

